### ISSUE TITLE
Not able to skip host identity check

### ISSUE THREAD

**Issue by amolkahat** [ansible/pylibssh#15]
Need option in session to skip host identity.

In `ansible.cfg` we can use.
```
host_key_checking=false
```

can we have same parameter like this?

**Comment by webknjaz** [comment]
@amolkahat I guess you're talking about exposing the corresponding API of libssh in Python, right?

**Comment by Akasurde** [comment]
@webknjaz Yes, I think so.

**Comment by ganeshrn** [comment]
@amolkahat Yes, I am working on adding support for this feature.
