### ISSUE TITLE
Error trying to use ed25519-sk key type that works with system SSH

### ISSUE THREAD

**Issue by astr0n8t** [ansible/pylibssh#509]
##### SUMMARY
Trying to use ed25519-sk key types which work with normal SSH does not work via pylibssh.  Instead it gives the following error:
```
"msg": "ssh connection failed: Failed to authenticate public key: The key algorithm 'sk-ssh-ed25519@openssh.com' is not allowed to be used by PUBLICKEY_ACCEPTED_TYPES configuration option"
```

##### ISSUE TYPE
- Bug Report

##### PYLISSH and LIBSSH VERSION

```paste below
ansible_pylibssh-1.1.0-cp311-cp311-macosx_10_9_universal2.whl

ansible [core 2.15.0]
  python version = 3.11.3 (main, Apr  7 2023, 19:25:52) [Clang 14.0.0 (clang-1400.0.29.202)] (/usr/local/Cellar/ansible/8.0.0/libexec/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

##### OS / ENVIRONMENT
macOS Ventura 13.4 -> VyOS 1.4 Rolling

##### STEPS TO REPRODUCE
Utilize ed25519-sk SSH key type and try to use this in conjunction with pylibssh.  I also have openssh installed via homebrew to add support for this key type.  Trying it out on Linux produces a similar error.

```paste below
- hosts: vyos
  name: Perform Initial Setup
  tags: [ always ]
  become: true
  gather_facts: false
  tasks:
    - name: configure name servers
      vyos.vyos.vyos_system:
        name_servers:
          - 1.1.1.1
          - 1.0.0.1
```

##### EXPECTED RESULTS
pylibssh should work with the same key types as when using the native SSH connection or offer a workaround to still utilize native SSH connections.

##### ACTUAL RESULTS
pylibssh complains that the key type is not accepted.  Trying to manually add this key type via ssh_args or ssh config does not help.

```paste below
The full traceback is:
  File "/Users/astr0n8t/.ansible/collections/ansible_collections/vyos/vyos/plugins/module_utils/network/vyos/vyos.py", line 58, in get_capabilities
    capabilities = Connection(module._socket_path).get_capabilities()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible/module_utils/connection.py", line 200, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
fatal: [vyos]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "domain_name": null,
            "domain_search": null,
            "host_name": null,
            "name_server": [
                "1.1.1.1",
                "1.0.0.1"
            ],
            "name_servers": [
                "1.1.1.1",
                "1.0.0.1"
            ],
            "state": "present"
        }
    },
    "msg": "ssh connection failed: Failed to authenticate public key: The key algorithm 'sk-ssh-ed25519@openssh.com' is not allowed to be used by PUBLICKEY_ACCEPTED_TYPES configuration option"
}
```

**Comment by kaN5300** [comment]
Hello. Similar problem here but with hmac-sha1 server side Kex algo. Running Debian GNU/Linux 12.2 inside proxmox LXC container with Python 3.12.0 compiled from source and virtualenv:

> Package            Version
> annotated-types    0.6.0
> ansible            8.5.0
> ansible-core       2.15.5
> ansible-pylibssh   1.1.0
> ansible-runner     2.3.4
> anyio              3.7.1
> asttokens          2.4.0
> backcall           0.2.0
> certifi            2023.7.22
> cffi               1.16.0
> charset-normalizer 3.3.0
> click              8.1.7
> cryptography       41.0.4
> decorator          5.1.1
> dnspython          2.4.2
> docutils           0.20.1
> email-validator    2.0.0.post2
> executing          2.0.0
> fastapi            0.103.2
> future             0.18.3
> gunicorn           21.2.0
> h11                0.14.0
> httpcore           0.18.0
> httptools          0.6.1
> httpx              0.25.0
> idna               3.4
> ipaddress          1.0.23
> ipython            8.16.1
> itsdangerous       2.1.2
> jedi               0.19.1
> Jinja2             3.1.2
> lockfile           0.12.2
> MarkupSafe         2.1.3
> matplotlib-inline  0.1.6
> orjson             3.9.9
> packaging          23.2
> parso              0.8.3
> pexpect            4.8.0
> pickleshare        0.7.5
> pip                23.3
> prompt-toolkit     3.0.39
> ptyprocess         0.7.0
> pure-eval          0.2.2
> pycparser          2.21
> pydantic           2.4.2
> pydantic_core      2.10.1
> Pygments           2.16.1
> python-daemon      3.0.1
> PyYAML             6.0.1
> requests           2.31.0
> resolvelib         1.0.1
> setuptools         68.2.2
> six                1.16.0
> sniffio            1.3.0
> stack-data         0.6.3
> starlette          0.27.0
> traitlets          5.11.2
> typing_extensions  4.8.0
> urllib3            2.0.6
> uvicorn            0.23.2
> wcwidth            0.2.8

Libssh system versions:
```
> dpkg -l | grep libssh
ii  libssh-4:amd64                  0.10.5-2                       amd64        tiny C SSH library (OpenSSL flavor)
ii  libssh-dev:amd64                0.10.5-2                       amd64        tiny C SSH library - Development files (OpenSSL flavor)
ii  libssh2-1:amd64                 1.10.0-3+b1                    amd64        SSH2 client-side library
```

Part of playbook:

```
---
- name: dcn play
  gather_facts: false
  hosts: dcn
  tasks:
    - name: port_show
      cisco.ios.command:
        commands: 'show run interface Ethernet1/0/{{ port_num }}'
      register: port_show
      when: port_num and task == 'port_show'
```

Failed output:
```
TASK [port_show] ***************************************************************
fatal: [172.16.105.180]: FAILED! => {"changed": false, "msg": "ssh connection failed: ssh connect failed: kex error : no match for method mac algo client->server: server [hmac-sha1], client [hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha2-256,hmac-sha2-512]"}
```

My temporary fix:

- pip uninstall ansible-pylibssh
- pip install paramiko

Result after fix:

```
TASK [port_show] ***************************************************************
[WARNING]: ansible-pylibssh not installed, falling back to paramiko
ok: [172.16.105.180]
```

Also tryed latest dev version, but code from readme fails with 404 error:

```
> pip install \
                                                                  --extra-index-url=https://ansible.github.io/pylibssh/simple/ \
                                                                  --pre \
                                                                  ansible-pylibssh
Looking in indexes: https://pypi.org/simple, https://ansible.github.io/pylibssh/simple/
Collecting ansible-pylibssh
  ERROR: HTTP error 404 while getting https://raw.githubusercontent.com/ansible/pylibssh/gh-pages/dist/ansible-pylibssh-1.1.1.dev51.tar.gz (from https://ansible.github.io/pylibssh/simple/ansible-pylibssh/)
ERROR: Could not install requirement ansible-pylibssh from https://raw.githubusercontent.com/ansible/pylibssh/gh-pages/dist/ansible-pylibssh-1.1.1.dev51.tar.gz because of HTTP error 404 Client Error: Not Found for url: https://raw.githubusercontent.com/ansible/pylibssh/gh-pages/dist/ansible-pylibssh-1.1.1.dev51.tar.gz for URL https://raw.githubusercontent.com/ansible/pylibssh/gh-pages/dist/ansible-pylibssh-1.1.1.dev51.tar.gz (from https://ansible.github.io/pylibssh/simple/ansible-pylibssh/)
```

**Comment by Qalthos** [comment]
PUBLICKEY_ACCEPTED_TYPES and HOSTKEYS can both now be overridden in pylibssh. Please look forward to a future netcommon release exposing these options

**Comment by denisbondar** [comment]
Can you please tell me how to use this in Ansible?
I get the following error:
```
ssh connection failed: Failed to authenticate public key: The key algorithm 'ssh-rsa' is not allowed to be used by PUBLICKEY_ACCEPTED_TYPES configuration option
```

**Comment by wdst-gcet** [comment]
I would like to know how to use this as well. Is there a way to set the `PUBLICKEY_ACCEPTED_TYPES` using an environment or Ansible var?
